# Generated by Django 4.1.7 on 2023-06-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0012_remove_clubaccount_address_and_more'),
    ]

    operations = [
    ]
