# Generated by Django 4.1.9 on 2023-06-16 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0014_movie_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEflix_Website.screen'),
        ),
    ]
