# Generated by Django 4.1.9 on 2023-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0016_alter_showing_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='social_distance',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
