# Generated by Django 4.1.9 on 2023-06-20 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UWEflix_Website', '0017_showing_social_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_movie',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='viewing_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='viewing_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='showing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEflix_Website.showing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
