# Generated by Django 4.1.9 on 2023-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0018_remove_booking_booked_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='columns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
