# Generated by Django 4.1.9 on 2023-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0019_screen_columns_screen_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='seats',
            field=models.JSONField(default=list),
        ),
    ]
