# Generated by Django 4.1.9 on 2023-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0022_remove_showing_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
