# Generated by Django 4.1.9 on 2023-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0023_showing_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='seats',
        ),
        migrations.AddField(
            model_name='screen',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showing',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
