# Generated by Django 4.1.9 on 2023-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0024_remove_showing_seats_screen_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='seat_layout',
            field=models.JSONField(default=list),
        ),
    ]
