# Generated by Django 4.1.7 on 2023-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0026_alter_booking_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubaccount',
            name='account_ID',
        ),
        migrations.AddField(
            model_name='clubaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, default=False, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
