# Generated by Django 4.1.7 on 2023-06-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0026_alter_booking_seats'),
    ]

    operations = [
    ]
