# Generated by Django 4.1.9 on 2023-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0027_remove_clubaccount_account_id_clubaccount_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
    ]
