# Generated by Django 4.1.9 on 2023-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0031_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adult',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
