# Generated by Django 4.1.9 on 2023-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0032_booking_adult_booking_children_booking_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.DecimalField(decimal_places=2, max_digits=6)),
                ('student', models.DecimalField(decimal_places=2, max_digits=6)),
                ('adult', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
