# Generated by Django 4.1.9 on 2023-06-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0033_ticketprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketPrice',
        ),
    ]
