# Generated by Django 4.1.9 on 2023-07-04 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0038_alter_club_club_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
