# Generated by Django 4.1.9 on 2023-07-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0039_club_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
