# Generated by Django 4.1.6 on 2023-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0042_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='social_distance',
        ),
    ]
