# Generated by Django 4.1.7 on 2023-06-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0004_rename_movie_movie_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seats',
        ),
    ]
