# Generated by Django 4.1.7 on 2023-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=3)),
                ('dateShowing', models.DateTimeField()),
                ('seats', models.IntegerField()),
            ],
        ),
    ]
