# Generated by Django 4.1.7 on 2023-06-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0003_remove_movie_dateshowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='movie_name',
        ),
    ]
