# Generated by Django 4.1.7 on 2023-06-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0005_remove_movie_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_showing', models.DateField(verbose_name='Movie Showing Date')),
                ('time_showing', models.TimeField(verbose_name='Movie Showing Time')),
                ('seats', models.IntegerField()),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UWEflix_Website.movie')),
            ],
        ),
    ]
