# Generated by Django 4.1.7 on 2023-06-15 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0007_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_num', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('seats', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='showing',
            name='date_showing',
            field=models.DateTimeField(verbose_name='Movie Showing Date'),
        ),
        migrations.AlterField(
            model_name='showing',
            name='time_showing',
            field=models.DateTimeField(verbose_name='Movie Showing Time'),
        ),
    ]
