# Generated by Django 4.1.7 on 2023-06-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0009_address_contact_clubaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubaccount',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UWEflix_Website.address'),
        ),
    ]
