# Generated by Django 4.1.7 on 2023-06-15 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0010_clubaccount_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
