# Generated by Django 4.1.7 on 2023-06-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEflix_Website', '0013_remove_clubaccount_id_alter_clubaccount_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
